#Instllilng Httpd

# Base OS - Centos 

FROM centos:latest

# Install Httpd Package
RUN yum install -y update && yum -y install httpd
 
# WORKINGDIR /var/www/html
WORKDIR /var/www/html/
# Copy index.html to /var/www/html/

COPY . . 

# Start the Service

CMD ["/usr/sbin/httd", "-D","FOREGROUND"]